[project]
name = "binwalk-python-sdk"
version = "0.1.0"
description = "Python bindings for running binwalk"
authors = [
    { name = "pUrGe12", email = "achintya.jai@owasp.org" }
]
license = "MIT"
readme = "README.md"
dependencies = []
classifiers = [
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[project.scripts]
binwalk-python-sdk = "binwalk_python_sdk:main"

[tool.maturin]
module-name = "binwalk_python_sdk._rust"
python-packages = ["binwalk_python_sdk"]
python-source = "src"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "src/**/*.rs" }, { file = "Cargo.toml" }, { file = "Cargo.lock" }]

[tool.isort]
profile = "black"
line_length = 99
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
known_first_party = ["pyba"]
no_inline_sort = true
skip = ["__init__.py", ".venv"]

[tool.ruff]
line-length = 99
per-file-ignores = { "__init__.py" = ["ALL"]}

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
